### ISSUE TITLE
The 

### ISSUE THREAD

**Issue by sandeepawsgit** [aws-samples/conversation-intelligence-using-aiml-on-aws#10]
I created a new AWS account to deploy this. The Deployment is failing at this screen. 

Please suggest how can we resolve the issue.

![image](https://github.com/aws-samples/conversation-intelligence-using-aiml-on-aws/assets/121190246/892232e1-10d7-457b-8ec0-d2cdd0c5e6b2)

**Comment by duttaanup** [comment]
@sandeepawsgit can you double check the  completion of step #2.5 https://github.com/aws-samples/conversation-intelligence-using-aiml-on-aws?tab=readme-ov-file#25-configure-huggingface-access-token-in-cfgpy
