### ISSUE TITLE
Diarization failed after running for more than 130 minutes

### ISSUE THREAD

**Issue by stravishankar** [aws-samples/conversation-intelligence-using-aiml-on-aws#2]
Diarization failed after running for more than 130 minutes, the file used was Auto0_GUID_000_AGENT_ChrisL_DT_2023-02-19T06-01-22_Mono.wav
{
  "cause": "Conversation Intelligence failed",
  "error": "Conversation Intelligence failed"
}

**Comment by duttaanup** [comment]
@stravishankar in the recent builds we have encountered the same and we are working on a fix for the same.

**Comment by duttaanup** [comment]
[stravishankar](https://github.com/stravishankar) we have update the docker file to support the latest CUDA runtime.
